remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: DWCJava - Enable Java for BBj
description: This is the homepage of the DWCJava project, which allows you to implement your PWA Progressive Web App for BBj directly in Java (or Kotlin)

theme: jekyll-theme-minimal